
[build]
  publish = "static"
  functions = "netlify/functions"

[dev]
  publish = "static"
  functions = "netlify/functions"
  
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfjs-dist"]
