<<<<<<< HEAD
=======

>>>>>>> d52d5154cd7a505dd585cba6a48684013ba230a6
[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[dev]
  command = "python main.py"
  port = 5000
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
<<<<<<< HEAD
  status = 200
=======
  status = 200
>>>>>>> d52d5154cd7a505dd585cba6a48684013ba230a6
