
[build]
  command = "chmod +x netlify.sh && ./netlify.sh"
  publish = "static"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api"
  status = 200
