
[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[dev]
  command = "python main.py"
  port = 5000
  publish = "static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
