[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "pdfplumber>=0.11.6",
    "pypdf2>=3.0.1",
    "requests>=2.32.3",
    "werkzeug>=3.1.3",
]
